Unpacking

In [1]:
a, b, c = 1, 2, 3
a, b, c

(1, 2, 3)

In [2]:
a, b, c = [1, 2, 3]
a, b, c

(1, 2, 3)

In [3]:
a, b, c = (2*i + 1 for i in range(3))
a, b, c

(1, 3, 5)

In [4]:
a, b, c = [2*i + 1 for i in range(3)]
a, b, c

(1, 3, 5)

In [5]:
a, (b, c), d = [1, (2, 3), 4]
a, b, c, d

(1, 2, 3, 4)

Unpacking for swapping variables

In [6]:
a, b = 1, 2
a, b = b, a
a, b

(2, 1)

Extended unpacking

In [7]:
a, *b, c = [1, 2, 3, 4, 5]
a, b, c

(1, [2, 3, 4], 5)

Negative indexing

In [14]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a[-1], a[-3], a[::-1], a[::-2], a[::2], a[::3]

(10,
 8,
 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
 [10, 8, 6, 4, 2, 0],
 [0, 2, 4, 6, 8, 10],
 [0, 3, 6, 9])

In [15]:
a = range(11)
a[-1], a[-3], a[::-1], a[::-2], a[::2], a[::3]

(10, 8, range(10, -1, -1), range(10, -1, -2), range(0, 11, 2), range(0, 11, 3))

List slices (a[start:end])

In [17]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a[2:8]

[2, 3, 4, 5, 6, 7]

List slices with negative indexing

In [18]:
a[-4:-2]

[7, 8]

List slices with step(a[start:end:step])

In [24]:
a[::2], a[2:9:2], a[2:10:2]

([0, 2, 4, 6, 8, 10], [2, 4, 6, 8], [2, 4, 6, 8])

List slice assignment

In [33]:
a = [1, 2, 3, 4, 5]
a[2:3] = 0, 0
a

[1, 2, 0, 0, 4, 5]

In [34]:
a[1:1] = 8, 9
a, len(a), a[1:3]

([1, 8, 9, 2, 0, 0, 4, 5], 8, [8, 9])

In [35]:
a[1] = 10
a

[1, 10, 9, 2, 0, 0, 4, 5]

Naming slices (slice(start, end, step))

In [38]:
a = [0, 1, 2, 3, 4, 5]
LASTTHREE = slice(-3, None)
LASTTHREE, a[LASTTHREE]

(slice(-3, None, None), [3, 4, 5])

In [44]:
a[slice(1, 3)], a[slice(1, None, 2)]

([1, 2], [1, 3, 5])

Iterating over list index and value pairs (enumarate)

In [48]:
a = ['Hello', 'word', '!']
for i, x in enumerate(a):
    print (i, x)

0 Hello
1 word
2 !


Iterating over dictionary key and value pairs (dict.items())

In [50]:
m = {'a': 1, 'b':2, 'c': 3, 'd':4}
for k, v in m.items():
    print (k, v)

a 1
b 2
c 3
d 4


Zipping and unzipping lists and iterables

In [57]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
z = zip(a, b)
z, list(z) # iterator, iterator converted to list

(<zip at 0x104463208>, [(1, 'a'), (2, 'b'), (3, 'c')])

In [63]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
z = zip(a, b)
z, set(z)

(<zip at 0x104431c88>, {(1, 'a'), (2, 'b'), (3, 'c')})

In [59]:
numbersList = [1, 2, 3]
strList = ['one', 'two']
numbersTuple = ('ONE', 'TWO', 'THREE', 'FOUR')
z = zip(numbersList, strList, numbersTuple)
set(z), list(z)

({(1, 'one', 'ONE'), (2, 'two', 'TWO')}, [])

In [64]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
z = zip(a, b)

c, v = zip(*z)
c, v

((1, 2, 3), ('a', 'b', 'c'))

Grouping adjacent list items using zip

In [67]:
a = [1, 2, 3, 4, 5, 6]
group_adjacent = lambda a, k: zip(*([iter(a)] * k))
g = group_adjacent(a, 3)
set(g)

{(1, 2, 3), (4, 5, 6)}

Inverting a dictionary using zip

In [73]:
m = {'a':1, 'b':2, 'c':3, 'd':4}
m.items()

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])

In [78]:
set(zip(m.values(), m.keys()))

{(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')}

In [80]:
dict(zip(m.values(), m.keys()))

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

Flattening lists

In [86]:
import itertools
a = [[1, 2], [3, 4], [5, 6]]
list(list(iter(aa)) for aa in a), list(itertools.chain.from_iterable(a))

([[1, 2], [3, 4], [5, 6]], [1, 2, 3, 4, 5, 6])

In [90]:
sum(a, []) # concatenate list to list

[1, 2, 3, 4, 5, 6]

In [92]:
[x for x in a]

[[1, 2], [3, 4], [5, 6]]

In [94]:
[x for l in a for x in l]

[1, 2, 3, 4, 5, 6]

In [96]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[x for l in a for l2 in l for x in l2]

[1, 2, 3, 4, 5, 6, 7, 8]

In [100]:
flatten = lambda x: [y for l in x for y in flatten(l)] if type(x) is list else [x]
flatten(a)

[1, 2, 3, 4, 5, 6, 7, 8]

In [99]:
type(a)

list

Generator expressions

In [103]:
g = (x ** 2 for x in range(10))
list(g)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [105]:
sum(x ** 3 for x in range(10))

2025

In [106]:
sum(x ** 3 for x in range(10) if x % 3 == 1)

408

Dictionary comprehensions

In [107]:
m = {x: x**2 for x in range(5)}
m

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [108]:
m = {x: 'A' + str(x) for x in range(10)}
m

{0: 'A0',
 1: 'A1',
 2: 'A2',
 3: 'A3',
 4: 'A4',
 5: 'A5',
 6: 'A6',
 7: 'A7',
 8: 'A8',
 9: 'A9'}

Inverting a dictionary using a dictionary comprehension

In [110]:
m = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
m
{v: k for k, v in m.items()}

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

In [3]:
import numpy as np

In [6]:
np.arange(10,25, 5)# incremental 1-D array: np.arange(start, end, step)

array([10, 15, 20])

In [7]:
np.linspace(0, 2, 9)# an array of evenly sapced values

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [9]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [12]:
np.random.random((2, 2))

array([[ 0.39909909,  0.22789154],
       [ 0.34082281,  0.58184172]])

In [13]:
np.empty((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.mgrid[0:5, 0:5] # dense meshgrid

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [15]:
np.ogrid[0:2, 0:2] # open meshgrid

[array([[0],
        [1]]), array([[0, 1]])]

In [18]:
from numpy import poly1d

In [19]:
poly1d((3, 4, 5))

poly1d([3, 4, 5])